# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHubRxMoyaExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHubRxMoyaExample
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'Moya', '~> 11.0'
  pod 'Moya/RxSwift', '~> 11.0'
  pod 'RxOptional'

end
